### ISSUE TITLE
Update to node20 env as node16 is being dropped

### ISSUE THREAD

**Issue by stronk7** [yashanand1910/standard-release-notes#31]
Current version of the action is warning, via annotations, about the deprecation of NodeJS 16:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: yashanand1910/standard-release-notes@v1.3.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

It would be great if the action can be updated to NodeJS 20.

Ciao :-)

**Comment by yashanand1910** [comment]
https://github.com/yashanand1910/standard-release-notes/compare/v1.3.0...v1.4.0

**Comment by stronk7** [comment]
Awesome, thanks!
